[tool.ruff]
line-length = 100
fix = true

[tool.ruff.lint]
select = ["E", "F", "W", "I", "ANN", "TCH", "TID",
#"D",  docstrings are turned off for now.
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["ALL"]