data:
  input_path: "data/diabetes.csv"
  target_column: "Diabetes"
  preprocessing:
    remove_outliers: false
    drop_in_fix_categorical: false
  feature_selection:
    enabled: false
    method: "correlation"
    top_k: 14
    threshold: 0.05

experiments:
  # logistic_regression:
  #   - name: "LR_baseline"
  #     params:
  #       C: 1.0
  #       max_iter: 1000
  #       solver: "lbfgs"
  #      use_cross_validation: false
  #     threshold: 0.2

  random_forest:
  
    - name: "RF_deepest"
      params:
        n_estimators: 300
        max_depth: 20
        max_features: 'sqrt'
        random_state: 42
        n_jobs: -1
        class_weight: "balanced"
      use_cross_validation: true
      threshold: 0.3
  # xgboost:
  #   - name: "XGB_Baseline"
  #     params:
  #       n_estimators: 200
  #       learning_rate: 0.05
  #       max_depth: 4
  #       subsample: 0.8
  #       colsample_bytree: 0.8
  #       scale_pos_weight: 2.3
  #       eval_metric: "logloss"
  #       use_label_encoder: false
  #     use_cross_validation: true
  #     threshold: 0.5
